# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addEditCoffeeForm(object):
    def setupUi(self, addEditCoffeeForm):
        addEditCoffeeForm.setObjectName("addEditCoffeeForm")
        addEditCoffeeForm.resize(279, 285)
        self.label_1 = QtWidgets.QLabel(addEditCoffeeForm)
        self.label_1.setGeometry(QtCore.QRect(30, 20, 47, 13))
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(addEditCoffeeForm)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(addEditCoffeeForm)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(addEditCoffeeForm)
        self.label_4.setGeometry(QtCore.QRect(30, 140, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(addEditCoffeeForm)
        self.label_5.setGeometry(QtCore.QRect(30, 180, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(addEditCoffeeForm)
        self.label_6.setGeometry(QtCore.QRect(30, 210, 47, 13))
        self.label_6.setObjectName("label_6")
        self.saveButton = QtWidgets.QPushButton(addEditCoffeeForm)
        self.saveButton.setGeometry(QtCore.QRect(100, 240, 75, 23))
        self.saveButton.setObjectName("saveButton")
        self.lineEdit_1 = QtWidgets.QLineEdit(addEditCoffeeForm)
        self.lineEdit_1.setGeometry(QtCore.QRect(100, 10, 151, 20))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(addEditCoffeeForm)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 50, 151, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(addEditCoffeeForm)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 90, 151, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(addEditCoffeeForm)
        self.lineEdit_4.setGeometry(QtCore.QRect(100, 130, 151, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(addEditCoffeeForm)
        self.lineEdit_5.setGeometry(QtCore.QRect(100, 170, 151, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(addEditCoffeeForm)
        self.lineEdit_6.setGeometry(QtCore.QRect(100, 210, 151, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")

        self.retranslateUi(addEditCoffeeForm)
        QtCore.QMetaObject.connectSlotsByName(addEditCoffeeForm)

    def retranslateUi(self, addEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        addEditCoffeeForm.setWindowTitle(_translate("addEditCoffeeForm", "Запись"))
        self.label_1.setText(_translate("addEditCoffeeForm", "Сорт"))
        self.label_2.setText(_translate("addEditCoffeeForm", "Обжарка"))
        self.label_3.setText(_translate("addEditCoffeeForm", "Помол"))
        self.label_4.setText(_translate("addEditCoffeeForm", "Вкус"))
        self.label_5.setText(_translate("addEditCoffeeForm", "Цена"))
        self.label_6.setText(_translate("addEditCoffeeForm", "Объем"))
        self.saveButton.setText(_translate("addEditCoffeeForm", "Сохранить"))
